### PR TITLE
Fix find nomenclature for geo 325

### LINKED ISSUE #325: Curator::Services::FactoryService#find_nomenclature_for_geographic doesn't find existing subjects
It appears the changes for https://github.com/boston-library/curator/commit/66c0a26588df04544c7b22b4d00059024743b258 may have impacted the ability to find existing subjects. This is resulting in records which have duplicative geographic subjects. (The dupes are added when the ingest is re-run and/or metadata is updated.)

For example:
```
obj = Curator::DigitalObject.find_by(ark_id: "commonwealth:m326q299j")

obj.descriptive.subject_geos.count
 => 10

obj.descriptive.subject_geos.map(&:authority_id)
 => [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]

obj.descriptive.subject_geos.map(&:label)
 => ["Boston", "Dorchester", "Boston", "Dorchester", "Boston", "Dorchester", "Boston", "Dorchester", "Boston", "Dorchester"]

obj.descriptive.subject_geos.map(&:id_from_auth)
 => ["7013445", "7013575", "7013445", "7013575", "7013445", "7013575", "7013445", "7013575", "7013445", "7013575"]

obj.descriptive.subject_geos.map(&:area_type)
 => ["city", "city_section", nil, nil, nil, nil, nil, nil, nil, nil]

obj.descriptive.subject_geos.map(&:coordinates)
 => ["42.35,-71.05", "42.2833,-71.0667", nil, nil, nil, nil, nil, nil, nil, nil]

obj.descriptive.subject_geos[6]
 => #<Curator::ControlledTerms::Geographic id: 375588, authority_id: 9, term_data: {"label"=>"Boston", "id_from_auth"=>"7013445"}, type: "Curator::ControlledTerms::Geographic", lock_version: 0, created_at: "2023-05-30 14:14:07.570964000 +0000", updated_at: "2023-05-30 14:14:07.570964000 +0000", label: "Boston", id_from_auth: "7013445", area_type: nil, coordinates: nil, bounding_box: nil>

obj.descriptive.subject_geos[8]
 => #<Curator::ControlledTerms::Geographic id: 377992, authority_id: 9, term_data: {"label"=>"Boston", "id_from_auth"=>"7013445"}, type: "Curator::ControlledTerms::Geographic", lock_version: 0, created_at: "2023-05-30 14:37:58.851925000 +0000", updated_at: "2023-05-30 14:37:58.851925000 +0000", label: "Boston", id_from_auth: "7013445", area_type: nil, coordinates: nil, bounding_box: nil>
```

### PR DESCRIPTION
**Pull request by bbarberBPL**
- Added new custom validator class that validates controlled terms `nomenclatures`  uniqueness by `id_from_auth` and `authority` that should prevent duplications
- Updated and added new specs
- Resolves #325

### CODE REVIEW

File: spec/validators/curator/controlled_terms/id_from_auth_uniqueness_validator_spec.rb
Comment (ebenenglish) [inline spec/validators/curator/controlled_terms/id_from_auth_uniqueness_validator_spec.rb:1]: Should we include a spec where we provide valid data and the validator doesn't throw an error?

File: spec/controllers/curator/institutions_controller_spec.rb [hunk 1]
```diff
@@ -34,6 +34,7 @@
       id_from_auth: location.id_from_auth,
       coordinates: location.coordinates,
       authority_code: location.authority_code,
+      bounding_box: location.bounding_box,
```
Comment (ebenenglish) [inline spec/controllers/curator/institutions_controller_spec.rb:37]: If I understand correctly, this is needed because the spec is referencing a previously-created geo subject fixture that contains a bounding box, yes?

File: spec/models/curator/controlled_terms/resource_type_spec.rb [hunk 2]
```diff
@@ -4,13 +4,25 @@
...
 require_relative '../shared/mappings/mapped_terms'
 
 RSpec.describe Curator::ControlledTerms::ResourceType, type: :model do
   it_behaves_like 'nomenclature'
   it_behaves_like 'authority_delegation'
 
+  it_behaves_like 'id_from_auth_uniqueness_validatable' do
+    # rubocop:disable RSpec/LetSetup
+    let!(:authority) { find_authority_by_code('resourceTypes') }
+    let!(:term_data) { { id_from_auth: 'foo', label: 'Foo' } } # NOTE: Had to use non standard term data here in order for spec to pass
```
Comment (ebenenglish) [inline spec/models/curator/controlled_terms/resource_type_spec.rb:18]: I think I get what's happening here, we might want to change this comment to be `using invalid data to test that validation fails as expected`. Then standardize this language across all the similar specs.

File: spec/models/curator/controlled_terms/language_spec.rb [hunk 3]
```diff
@@ -4,12 +4,24 @@
...
 require_relative '../shared/controlled_terms/reindex_descriptable'
 require_relative '../shared/mappings/mapped_terms'
 RSpec.describe Curator::ControlledTerms::Language, type: :model do
   it_behaves_like 'nomenclature'
   it_behaves_like 'authority_delegation'
 
+  it_behaves_like 'id_from_auth_uniqueness_validatable' do
+    # rubocop:disable RSpec/LetSetup
+    let!(:authority) { find_authority_by_code('iso639-2') }
+    let!(:term_data) { { id_from_auth: 'bar', label: 'Bar' } }
```
Comment (ebenenglish) [inline spec/models/curator/controlled_terms/language_spec.rb:17]: add comment about invalid data

File: spec/models/curator/controlled_terms/genre_spec.rb [hunk 4]
```diff
@@ -4,13 +4,25 @@
...
 require_relative '../shared/mappings/mapped_terms'
 
 RSpec.describe Curator::ControlledTerms::Genre, type: :model do
   it_behaves_like 'nomenclature'
   it_behaves_like 'authority_delegation'
 
+  it_behaves_like 'id_from_auth_uniqueness_validatable' do
+    # rubocop:disable RSpec/LetSetup
+    let!(:authority) { find_authority_by_code('gmgpc') }
+    let!(:term_data) { { id_from_auth: 'tgm008084' } }
```
Comment (ebenenglish) [inline spec/models/curator/controlled_terms/genre_spec.rb:18]: add comment about using invalid data

File: spec/models/curator/controlled_terms/name_spec.rb [hunk 5]
```diff
@@ -4,13 +4,25 @@
...
 require_relative '../shared/mappings/mapped_terms'
 
 RSpec.describe Curator::ControlledTerms::Name, type: :model do
   it_behaves_like 'nomenclature'
   it_behaves_like 'authority_delegation'
 
+  it_behaves_like 'id_from_auth_uniqueness_validatable' do
+    # rubocop:disable RSpec/LetSetup
+    let!(:authority) { find_authority_by_code('gmgpc') }
+    let!(:term_data) { { id_from_auth: 'tgm008084' } }
```
Comment (ebenenglish) [inline spec/models/curator/controlled_terms/name_spec.rb:18]: add comment about invalid data

**Review by ebenenglish — CHANGES_REQUESTED** [review]
Looks good overall, great work! Just a couple of questions and thoughts.

File: spec/controllers/curator/institutions_controller_spec.rb (hunk 1 above)
Comment (bbarberBPL) [reply spec/controllers/curator/institutions_controller_spec.rb:37]: Yes that is correct

**Review by ebenenglish — APPROVED** [review]
