### PR TITLE
Fix 287

### LINKED ISSUE #287: XML serialization for multipart coporate names
In some cases multipart corporate name subjects are getting serialized incorrectly in the MODS XML serialization, and in some cases are not getting serialized at all.

This issue seems to specifically affect subjects where the label value is being split on a "." character.

### Incorrect:
Example ARK id: `commonwealth:cn69ms10n`

**JSON:**
```json
"name_roles": [
  {
    "name":{
      "label":"United States. Work Projects Administration",
      "id_from_auth":"n80046793",
      "authority_code":"naf",
      "name_type":"corporate"
    },
    "role":{
      "label":"Sponsor",
      "id_from_auth":"spn",
      "authority_code":"marcrelator"
    }
  }
]
```
**MODS:**
This:
```xml
<mods:name type="corporate" authority="naf" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/n80046793">
  <mods:namePart>United States</mods:namePart>
  <mods:role>
    <mods:roleTerm type="text" authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators" valueURI="http://id.loc.gov/vocabulary/relators/spn">Sponsor</mods:roleTerm>
  </mods:role>
</mods:name>
```
Should be:
```xml
<mods:name type="corporate" authority="naf" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/n80046793">
  <mods:namePart>United States</mods:namePart>
  <mods:namePart>Work Projects Administration</mods:namePart>
  <mods:role>
    <mods:roleTerm type="text" authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators" valueURI="http://id.loc.gov/vocabulary/relators/spn">Sponsor</mods:roleTerm>
  </mods:role>
</mods:name>
```

### Missing:
Example ARK id: `commonwealth:gt54m914h`

**JSON:**
```json
"subject":{
  "names":[
    {
      "label":"Boston Public Library. South Boston Branch Library",
      "authority_code":"local",
      "name_type":"corporate"
    }
  ]
}
```

Example ARK id: `commonwealth:3f463h499`

**JSON:**
```json
"subject":{
  "names":[
    {
      "label":"Boston Public Library. Allston Branch Library",
      "authority_code":"local",
      "name_type":"corporate"
    }
  ]
}
```

Once this is fixed, we will need to identify affected records and reindex them to regenerate the MODS XML value in the Solr record.

### PR DESCRIPTION
**Pull request by bbarberBPL**
- Fixed bug in `Curator::Parsers::InputParser.corp_name_part_splitter` 
- Fixes #287
- Updated some gem dependencies
- Added forward slash to unicode characters in fixtures to ensure they encode properly
- Updated specs

### CODE REVIEW

File: spec/services/curator/digital_object_factory_service_spec.rb [hunk 1]
```diff
@@ -171,7 +171,7 @@
           let(:json_names) { desc_json['name_roles'].map { |nr| nr['name'] } }
           let(:json_roles) { desc_json['name_roles'].map { |nr| nr['role'] } }
           it 'sets the correct number of names and roles' do
-            expect(name_roles.count).to eq 2
+            expect(name_roles.count).to be >= 2
```
Comment (ebenenglish) [inline spec/services/curator/digital_object_factory_service_spec.rb:174]: Would prefer to keep this an `eq` comparison with an exact number of expected results, just seems a little more reliable.

**Review by ebenenglish — COMMENTED** [review]
Looks good, just one tiny fix if you don't mind?

File: spec/services/curator/digital_object_factory_service_spec.rb (hunk 1 above)
Comment (bbarberBPL) [reply spec/services/curator/digital_object_factory_service_spec.rb:174]: Ok I actually added an additional `name_role` to the fixture that's being used in this example to ill just put `eq 3` in this case
