### PR TITLE
Fixes #171

### LINKED ISSUE #171: Fix No Method error undefined method exist? for ExemplaryImage mapping
During a test export this eror kept repeating

`the export failed with status: 500. Error: {"errors":[{"status":500,"t
itle":"Internal Server Error","detail":"undefined method `exist?' for #\u003cCurator::Mappings::ExemplaryImage`

I believe this happens in a factory service due to a typo.

### PR DESCRIPTION
**Pull request by bbarberBPL**
Fixed the error referenced in #171 

Touched up a couple things in the digital object factory service

Changed check for extensions in first migration

### CODE REVIEW

File: app/services/curator/digital_object_factory_service.rb [hunk 1]
```diff
@@ -109,7 +109,7 @@ def find_or_build_collection_members!(digital_object, admin_set_ark_id, collecti
 
           collection = Curator.collection_class.select(:id, :ark_id).find_by!(ark_id: collection_ark_id)
 
-          next if digital_object.collection_members.exists?(collection: collection)
+          next if digital_object.new_record? || digital_object.collection_members.exists?(collection: collection)
```
Comment (ebenenglish) [inline app/services/curator/digital_object_factory_service.rb:112]: I'm confused by this. Why would we skip `digital_object.collection_members.build` if this is a new record?
